package com.example.yin.dao;

import com.example.yin.domain.SongList;

public interface SongListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int insert(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int insertSelective(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    SongList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SongList record);
}